CREATE TABLE USPNECASA.SESSION (
	PRIMARY_ID CHAR(36) NOT NULL,
	SESSION_ID CHAR(36) NOT NULL,
	CREATION_TIME BIGINT NOT NULL,
	LAST_ACCESS_TIME BIGINT NOT NULL,
	MAX_INACTIVE_INTERVAL INT NOT NULL,
	EXPIRY_TIME BIGINT NOT NULL,
	PRINCIPAL_NAME VARCHAR(100),
	CONSTRAINT SESSION_PK PRIMARY KEY (PRIMARY_ID)
) IN DATABASE USPNDB;

CREATE UNIQUE INDEX USPNECASA.SESSION_IX1 ON USPNECASA.SESSION (SESSION_ID);
CREATE INDEX USPNECASA.SESSION_IX2 ON USPNECASA.SESSION (EXPIRY_TIME);
CREATE INDEX USPNECASA.SESSION_IX3 ON USPNECASA.SESSION (PRINCIPAL_NAME);

CREATE TABLE USPNECASA.SESSION_ATTRIBUTES (
	SESSION_PRIMARY_ID CHAR(36) NOT NULL,
	ATTRIBUTE_NAME VARCHAR(200) NOT NULL,
	ATTRIBUTE_BYTES BLOB NOT NULL,
	CONSTRAINT SESSION_ATTRIBUTES_PK PRIMARY KEY (SESSION_PRIMARY_ID, ATTRIBUTE_NAME),
	CONSTRAINT SESSION_ATTRIBUTES_FK FOREIGN KEY (SESSION_PRIMARY_ID) REFERENCES USPNECASA.SESSION(PRIMARY_ID) ON DELETE CASCADE
) IN DATABASE USPNDB;
