//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.04 at 09:18:15 AM MSK 
//


package com.rstyle.pfr.ecasa.auth.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rstyle.pfr.ecasa.auth.ws package. 
 * &lt;p&gt;An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _IsLoggedIn_QNAME = new QName("http://ws.auth.ecasa.pfr.rstyle.com/", "isLoggedIn");
    private final static QName _IsLoggedInResponse_QNAME = new QName("http://ws.auth.ecasa.pfr.rstyle.com/", "isLoggedInResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rstyle.pfr.ecasa.auth.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IsLoggedIn }
     * 
     */
    public IsLoggedIn createIsLoggedIn() {
        return new IsLoggedIn();
    }

    /**
     * Create an instance of {@link IsLoggedInResponse }
     * 
     */
    public IsLoggedInResponse createIsLoggedInResponse() {
        return new IsLoggedInResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsLoggedIn }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.auth.ecasa.pfr.rstyle.com/", name = "isLoggedIn")
    public JAXBElement<IsLoggedIn> createIsLoggedIn(IsLoggedIn value) {
        return new JAXBElement<IsLoggedIn>(_IsLoggedIn_QNAME, IsLoggedIn.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsLoggedInResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.auth.ecasa.pfr.rstyle.com/", name = "isLoggedInResponse")
    public JAXBElement<IsLoggedInResponse> createIsLoggedInResponse(IsLoggedInResponse value) {
        return new JAXBElement<IsLoggedInResponse>(_IsLoggedInResponse_QNAME, IsLoggedInResponse.class, null, value);
    }

}
