//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.04 at 09:18:15 AM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.auth.ecasa.pfr.rstyle.com/")
package com.rstyle.pfr.ecasa.auth.ws;
